# Generated by Django 2.2.6 on 2019-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_accuracydetails_customerrawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOBMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=100)),
                ('dob_flg', models.BooleanField()),
                ('year_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NameMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=100)),
                ('cosine_percentage', models.IntegerField()),
                ('reorder_flg', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccuracyDetails',
        ),
        migrations.DeleteModel(
            name='CustomerRawData',
        ),
        migrations.RenameField(
            model_name='customerdata',
            old_name='customer_id',
            new_name='cust_id',
        ),
    ]
