# Generated by Django 2.2.6 on 2019-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_auto_20191019_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namematch',
            name='cosine_percentage',
            field=models.CharField(max_length=100),
        ),
    ]
