# Generated by Django 2.2.6 on 2019-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_auto_20191019_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobmatch',
            name='cust_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dobmatch',
            name='dob_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dobmatch',
            name='year_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='namematch',
            name='cust_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='namematch',
            name='reorder_flg',
            field=models.BooleanField(default=False),
        ),
    ]
